---
mongo:
  image: mongo:2.6
content:
  image: quay.io/deconst/content-service
  links:
  - "mongo:mongo"
  environment:
    RACKSPACE_USERNAME:
    RACKSPACE_APIKEY:
    RACKSPACE_REGION: DFW
    CONTENT_CONTAINER: deconst-dev-content
    ASSET_CONTAINER: deconst-dev-assets
    MONGODB_URL: mongodb://mongo:27017/content
    CONTENT_LOG_LEVEL: DEBUG
  ports:
  - "9000:8080"
presenter:
  build: .
  links:
  - content
  environment:
    CONTENT_SERVICE_URL: http://content:8080/
    PRESENTED_URL_PROTO: https
    PRESENTED_URL_DOMAIN: mysite.com
    PRESENTER_LOG_LEVEL: DEBUG
  ports:
  - "80:8080"
  volumes:
  - ".:/usr/src/app"
  command: script/dev
